# Generated by Django 5.2.16 on 2026-07-30 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_guest', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chioce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=400)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory', models.CharField(choices=[('FEEDBACK', 'Feedback'), ('REVIEW', 'Review'), ('REGULER', 'Reguler'), ('OTHER', 'Other')], default='REGULER', max_length=20)),
                ('question', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('NUMBER', 'Number'), ('CHIOCE', 'Chioce'), ('DATE', 'Date'), ('TEXT', 'Text')], default='TEXT', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chioce', to='eventier_base.chioce')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.attendee')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.customfield')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.customuser'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('banner', models.FileField(upload_to='event_banners/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('postponed_date', models.DateTimeField(blank=True, null=True)),
                ('event_orgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customfield',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='eventier_base.event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.event'),
        ),
    ]
