# Generated by Django 5.2.16 on 2026-07-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory', models.CharField(choices=[('FEEDBACK', 'Feedback'), ('REVIEW', 'Review'), ('REGULER', 'Reguler'), ('OTHER', 'Other')], default='REGULER', max_length=20)),
                ('question', models.CharField(max_length=200)),
                ('field_type', models.CharField(default='text', max_length=30)),
                ('choice', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.attendee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.custom_field')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.custom_user'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('banner', models.FileField(upload_to='event_banners/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_orgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.custom_user')),
            ],
        ),
        migrations.AddField(
            model_name='custom_field',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='eventier_base.event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.event'),
        ),
    ]
