# Generated by Django 5.2.16 on 2026-07-31 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventier_base', '0002_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chioce',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
