# Generated by Django 5.2.16 on 2026-07-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventier_base', '0002_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
