# Generated by Django 5.2.16 on 2026-07-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventier_base', '0004_alter_attendee_id_alter_customanswer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventier_base.customfield'),
        ),
    ]
